# Node version
ARG NODE_VERSION=20.9.0

# ------------------------------------------------------FRONTEND

FROM node:${NODE_VERSION} as FRONTEND

LABEL maintainer="2023 MyHomeworks, { }"

WORKDIR /app

COPY ./.env .

WORKDIR /app/Client

COPY ./Client/package.json .

RUN npm install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false

COPY ./Client .

RUN npm run build

RUN rm -rf node_modules && \
  NODE_ENV=production npm install \
  --prefer-offline \
  --pure-lockfile \
  --non-interactive \
  --production=true