# Node version
ARG NODE_VERSION=20.9.0

# ------------------------------------------------------FRONTEND

FROM node:${NODE_VERSION} as frontend

LABEL maintainer="2023 MyHomeworks, { }"

WORKDIR /app/Client

COPY ./Client .

RUN npm install
RUN npm run build

EXPOSE 3000

WORKDIR /app

COPY .env .

WORKDIR /app/Client
