# Python version
ARG PYTHON_VERSION=3.10.11

# ------------------------------------------------------BACKEND

FROM python:${PYTHON_VERSION} as backend

LABEL maintainer="2023 MyHomeworks, { }"

ENV PYTHONUNBUFFERED=1

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . .

# remove all unnecessary files and folders
RUN rm -rf Client/ && rm -rf db_data/ && rm -r django_logs/ && rm -r gunicorn_logs/ && rm -rf nginx/ && rm -rf screenshots/ && rm -rf staticfiles/ && rm -rf taggitBugFix/

# bug fix (with help of ./serializers.py) in taggit_serializer library
# ----->
WORKDIR /usr/local/lib/python3.10/site-packages/taggit_serializer/

COPY ./taggitBugFix/serializers.py .
# <-----

WORKDIR /app
