# Generated by Django 5.0 on 2023-12-28 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog__main', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='IMG', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(verbose_name='URL'),
        ),
    ]
