# Generated by Django 5.0 on 2023-12-30 20:41

import Blog__main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog__main', '0003_alter_post_image_alter_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number must contain only 11 digits in format _(___)___-__-__.', max_length=15, null=True, unique=True, validators=[Blog__main.models.validate_phone], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
