# Generated by Django 5.0 on 2023-12-30 20:59

import Blog__main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog__main', '0004_alter_user_phone_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Phone number should contain only 11 digits in format _(___)___-__-__.', max_length=15, null=True, unique=True, validators=[Blog__main.models.validate_phone], verbose_name='Phone number'),
        ),
    ]
