# Generated by Django 5.0 on 2024-01-02 22:23

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog__main', '0005_alter_user_phone'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
        migrations.AddField(
            model_name='post',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
